/*
   PrlApiMacro.h

   In some situations we need a complete list of the API library
   functions to be accessible in one easy step. A good example
   would be the dynamic loading of the library. It seems like a
   good idea to keep such a list declared in a single file. This
   will make the future code support easier. The PrlApiMacro.h
   \file serves this purpose. The following steps illustrate how
   this file can be used:
     1. Define your own PRL_SDK_WRAP_FOR_EACH_ITERATOR:
   \#define PRL_SDK_WRAP_FOR_EACH_ITERATOR( method )
     2. Include the PrlApiMacro.h file in your source:
   \#include "PrlApiMacro.h"
     3. Instantiate the PRL_SDK_WRAP_FOR_EACH( ) macro to
        execute your specific action for each API method.
   Note
   This file contains just a list of names. No static/dynamic
   type information declared here at all.

   Copyright (c) Parallels International GmbH.
   All rights reserved. http://www.parallels.com            */
#ifndef PRL_SDK_WRAP_FOR_EACH

#include "PrlApiDeprMacro.h"
#include "PrlApiMgrMacro.h"

#define PRL_SDK_WRAP_FOR_EACH() \
PRL_SDK_WRAP_FOR_EACH_DEPRECATED() \
PRL_SDK_WRAP_FOR_EACH_MANAGER() \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_Init ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_InitEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_Deinit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetAppMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetResultDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetMessageType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_MsgCanBeIgnored ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetCrashDumpsPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_InitCrashHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBuffer_Free ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_CreateStringsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_CreateHandlesList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_CreateOpTypeList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetSupportedOsesTypes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetSupportedOsesVersions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetDefaultOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_SendPackedProblemReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStrList_GetItemsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStrList_AddItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStrList_GetItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStrList_RemoveItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHndlList_GetItemsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHndlList_AddItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHndlList_GetItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHndlList_RemoveItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOpTypeList_GetItemsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOpTypeList_AddItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOpTypeList_GetItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOpTypeList_RemoveItem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOpTypeList_GetTypeSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_RegisterRemoteDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_UnregisterRemoteDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRemoteDeviceRegistration ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_SendRemoteCommand )		 \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRemoteCommandTarget ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRemoteCommandIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRemoteCommandCode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRemoteCommandBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_CreateRemoteCommand ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_GetRecommendMinVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_ScaleImage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_AddRef ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_Free ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDbg_GetHandlesNum ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDbg_PrlResultToString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDbg_HandleTypeToString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDbg_EventTypeToString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_Wait ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_Cancel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetProgress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetRetCode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetDataPtr ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetResult ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetError ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_GetOpCode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlJob_IsRequestWasSent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlResult_GetParamsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlResult_GetParamByIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlResult_GetParam ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlResult_GetParamByIndexAsString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlResult_GetParamAsString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetDataPtr ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetServer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetJob ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetParamsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetParam ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetParamByName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetErrCode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetErrString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_CanBeIgnored ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_IsAnswerRequired ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetIssuerType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_GetIssuerId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_CreateAnswerEvent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToCData ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToUint32 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToInt32 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToUint64 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToInt64 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToBoolean ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_ToHandle ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvtPrm_GetBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LookupParallelsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CheckParallelsServerAlive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CheckParallelsServerAliveEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_Login ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ProxyLogin ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LoginLocal ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetHost ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetHost ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetPortNumber ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetPortNumber ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetUser ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetUser ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetPasswd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetPasswd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetSocketPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetSocketPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetPrevSessionUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetPrevSessionUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetSecurityLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetSecurityLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetTimeout ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetTimeout ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetUserIdentity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetUserIdentity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_GetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginParams_SetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_Logoff ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RegEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UnregEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetQuestions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SetNonInteractiveSession ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_IsNonInteractiveSession ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_DisableConfirmationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_EnableConfirmationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_IsConfirmationModeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetSrvConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetCommonPrefs ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CommonPrefsBeginEdit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CommonPrefsCommit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CommonPrefsCommitEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetUserProfile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetUserInfoList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetUserInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UpdateSessionInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetVirtualNetworkList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_AddVirtualNetwork ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UpdateVirtualNetwork ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_DeleteVirtualNetwork ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ConfigureGenericPci ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UserProfileBeginEdit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UserProfileCommit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_IsConnected ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetServerInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RegisterVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RegisterVmEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RegisterVmWithUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RegisterVmWithParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CreateVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetVmList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetVmListEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SubscribeToHostStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UnsubscribeFromHostStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_Shutdown ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ShutdownEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsGetDiskList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsGetDirEntries ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsCreateDir ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsRemoveEntry ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsCanCreateFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsRenameEntry ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UpdateLicense ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UpdateLicenseEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_InstallLicenseOffline ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ActivateTrialLicense ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_DeactivateInstalledLicense ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetLicenseInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SendAnswer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_StartSearchVms ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsInfo_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsInfo_GetFsType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsInfo_GetChildEntriesCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsInfo_GetChildEntry ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsInfo_GetParentEntry ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetAbsolutePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetRelativeName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetLastModifiedDate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetPermissions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFsEntry_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_NetServiceStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_NetServiceStop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_NetServiceRestart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_NetServiceRestoreDefaults ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetNetServiceStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetPackedProblemReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_AttachToLostTask ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetSupportedOses ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetDisplayEncodingList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetCpuModel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetCpuCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetCpuSpeed ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetCpuHvt ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetCpuType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostOsType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostOsMajor ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostOsMinor ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostOsSubMinor ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostOsStrPresentation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_IsSoundDefaultEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_IsUsbSupported ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_IsVtdSupported ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetMaxHostNetAdapters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetMaxVmNetAdapters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHostname ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetDefaultGateway ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetDefaultGatewayIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetFloppyDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetFloppyDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetOpticalDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetOpticalDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSerialPortsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSerialPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetParallelPortsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetParallelPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSoundOutputDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSoundOutputDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSoundMixerDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetSoundMixerDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetPrintersCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetPrinter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetGenericPciDevicesCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetGenericPciDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetGenericScsiDevicesCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetGenericScsiDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetUsbDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetUsbDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHardDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetHardDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetNetAdaptersCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfg_GetNetAdapter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_IsConnectedToVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetDeviceState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_SetDeviceState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetVmUuidCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgDev_GetVmUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetDevName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetDevId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetDevSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetDiskIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetPartsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHdd_GetPart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_GetSysName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_GetIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_IsInUse ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_IsLogical ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgHddPart_IsActive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetNetAdapterType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetSysIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_IsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_IsConfigureWithDhcp ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_IsConfigureWithDhcpIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetDefaultGateway ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetDefaultGatewayIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetMacAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetVlanTag ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetNetAddresses ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgNet_GetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgPci_GetDeviceClass ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvCfgPci_IsPrimaryDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_GetVmDirUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_SetVmDirUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_GetDefaultVmFolder ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_SetDefaultVmFolder ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_CanUseMngConsole ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_CanChangeSrvSets ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrCfg_IsLocalAdministrator ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrInfo_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrInfo_GetUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrInfo_GetSessionCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrInfo_GetDefaultVmFolder ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsrInfo_CanChangeSrvSets ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSessionInfo_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetDefaultVmDir ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetReservedMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetReservedMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMinVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMinVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMaxVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMaxVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetRecommendMaxVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetRecommendMaxVmMem ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMaxReservMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMaxReservMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMinReservMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMinReservMemLimit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAdjustMemAuto ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetAdjustMemAuto ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsSendStatisticReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetSendStatisticReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_CanChangeDefaultSettings ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetCanChangeDefaultSettings ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMinSecurityLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMinSecurityLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetConfirmationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetConfirmationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetPasswordProtectedOperationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetPasswordProtectedOperationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsVerboseLogEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetVerboseLogEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsDisableDeletingReportArchive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetDisableDeletingReportArchive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAddSerialPortOutputToReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetAddSerialPortOutputToReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAllowMultiplePMC ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetAllowMultiplePMC ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAllowDirectMobile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetAllowDirectMobile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAllowMobileClients ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetProxyConnectionStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetProxyConnectionCreds ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetProxyConnectionUser ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetPaxSupportModeStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetPaxSupportModeStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsLogRotationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetLogRotationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsAllowAttachScreenshotsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetAllowAttachScreenshotsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_IsLockedSign ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetNetworkId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetNetworkId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetNetworkType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetNetworkType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetBoundCardMac ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetBoundCardMac ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetAdapterName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetAdapterName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetAdapterIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetAdapterIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetHostIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetHostIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetHostIP6Address ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetHostIP6Address ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetDhcpIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetDhcpIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetDhcpIP6Address ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetDhcpIP6Address ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIPNetMask ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIPNetMask ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIP6NetMask ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIP6NetMask ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetVlanTag ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetVlanTag ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIPScopeStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIPScopeStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIPScopeEnd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIPScopeEnd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIP6ScopeStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIP6ScopeStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetIP6ScopeEnd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetIP6ScopeEnd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsAdapterEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetAdapterEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsDHCPServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetDHCPServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsDHCP6ServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetDHCP6ServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsNATServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetNATServerEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetPortForwardList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetPortForwardList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_GetBoundAdapterInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_SetHostAssignIP6) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVirtNet_IsHostAssignIP6) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_GetRuleName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_SetRuleName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_GetIncomingPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_SetIncomingPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_GetRedirectIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_SetRedirectIPAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_GetRedirectPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_SetRedirectPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_GetRedirectVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlPortFwd_SetRedirectVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Start ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_StartEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Restart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Stop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_StopEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Pause ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Reset ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Suspend ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ChangeSid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ResetUptime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetSuspendedScreen ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Resume ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_DropSuspendedState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CreateSnapshot ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SwitchToSnapshot ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SwitchToSnapshotEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_DeleteSnapshot ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetSnapshotsTree ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetSnapshotsTreeEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Lock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Unlock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UpdateSnapshotData ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Clone ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CloneEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GenerateVmDevFilename ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Delete ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetPackedProblemReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_RefreshConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_LoginInGuest ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_StartVncServer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_StopVncServer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuest_Logout ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuest_RunProgram ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuest_GetNetworkSettings ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuest_SetUserPasswd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SetConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDefaultConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDefaultConfigEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_TuneDefaultConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsConfigInvalid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetConfigValidity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_AddDefaultDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_AddDefaultDeviceEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsDefaultDeviceNeeded ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDefaultMemSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDefaultHddSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDefaultVideoRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetStatisticsEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SubscribeToGuestStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UnsubscribeFromGuestStatistics ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Reg ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_RegEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Unreg ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Restore ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_BeginEdit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Commit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CommitEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_CreateVmDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAccessRights ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAllDevices ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDevsCountByType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDevByType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetFloppyDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetFloppyDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHardDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHardDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetOpticalDisksCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetOpticalDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetParallelPortsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetParallelPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSerialPortsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSerialPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSoundDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSoundDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUsbDevicesCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUsbDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetNetAdaptersCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetNetAdapter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetGenericPciDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetGenericPciDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetGenericScsiDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetGenericScsiDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDisplayDevsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDisplayDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_CreateShare ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSharesCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetShare ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartGuardEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartGuardEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartGuardNotifyBeforeCreation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartGuardNotifyBeforeCreation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSmartGuardInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartGuardInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSmartGuardMaxSnapshotsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartGuardMaxSnapshotsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUserDefinedSharedFoldersEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUserDefinedSharedFoldersEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedCloudEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedCloudEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetModalityOpacity) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetModalityOpacity) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsModalityStayOnTop) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetModalityStayOnTop) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsModalityShowOnAllSpaces) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetModalityShowOnAllSpaces) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsModalityCaptureMouseClicks) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetModalityCaptureMouseClicks) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsFullscreenUseAllDisplays) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFullscreenUseAllDisplays) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsFullscreenActivateSpacesOnClick) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFullscreenActivateSpacesOnClick) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsFullscreenOptimizeForGames) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFullscreenOptimizeForGames) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsFullscreenGammaControl) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFullscreenGammaControl) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetFullscreenScaleViewMode) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFullscreenScaleViewMode) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartMountEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartMountEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartMountRemovableDrivesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartMountRemovableDrivesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartMountDVDsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartMountDVDsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartMountNetworkSharesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartMountNetworkSharesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedProfileEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedProfileEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseDesktop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseDesktop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseDocuments ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseDocuments ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUsePictures ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUsePictures ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseMusic ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseMusic ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseDownloads ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseDownloads ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseMovies ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseMovies ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsAutoCaptureReleaseMouse ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoCaptureReleaseMouse ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmartMouseEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmartMouseEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsStickyMouseEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetStickyMouseEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSmoothScrollingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmoothScrollingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetOptimizeModifiersMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetOptimizeModifiersMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShareClipboard ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShareClipboard ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsToolsAutoUpdateEnabled) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetToolsAutoUpdateEnabled) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsTimeSynchronizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTimeSynchronizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSyncTimezoneDisabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSyncTimezoneDisabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsTimeSyncSmartModeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTimeSyncSmartModeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetTimeSyncInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTimeSyncInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsAllowSelectBootDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAllowSelectBootDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_CreateScrRes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetScrResCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetScrRes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_RegEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UnregEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetQuestions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_CreateBootDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetBootDevCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetBootDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHostname ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHostname ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetLinkedVmUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetOsType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsRamAutoSizeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetRamAutoSizeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetVideoRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetVideoRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetVideoAdapterType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetVideoAdapterType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsApertureOnlyCapable ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHostMemQuotaMax ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHostMemQuotaMax ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHostMemQuotaPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHostMemQuotaPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsHostMemAutoQuota ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHostMemAutoQuota ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetMaxBalloonSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetMaxBalloonSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetCpuCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCpuCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsCpuAutoCountEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCpuAutoCountEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetCpuType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCpuType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetCpuAccelLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCpuAccelLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsCpuVtxEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsCpuHotplugEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCpuHotplugEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetChipsetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetChipsetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetChipsetVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetChipsetVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_Get3DAccelerationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_Set3DAccelerationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsVerticalSynchronizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetVerticalSynchronizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsHighResolutionEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHighResolutionEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsHighResolutionInGuestEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHighResolutionInGuestEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsNativeScalingInGuestEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetNativeScalingInGuestEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHypervisorType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHypervisorType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsAdaptiveHypervisorEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAdaptiveHypervisorEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSwitchOffWindowsLogoEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSwitchOffWindowsLogoEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsLongerBatteryLifeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetLongerBatteryLifeEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsBatteryStatusEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetBatteryStatusEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsNestedVirtualizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetNestedVirtualizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsPMUVirtualizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetPMUVirtualizationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsLockGuestOnSuspendEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetLockGuestOnSuspendEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsIsolatedVmEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetIsolatedVmEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTpmType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetServerUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetServerHost ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetHomePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetLocation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetIcon ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetIcon ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsTemplate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTemplateSign ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetCustomProperty ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCustomProperty ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAutoStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAutoStartDelay ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoStartDelay ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetStartLoginMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetStartLoginMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetStartUserLogin ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetStartUserCreds ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAutoStop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoStop ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetActionOnWindowClose ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetActionOnWindowClose ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetActionOnStopMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetActionOnStopMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetWindowMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetWindowMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsStartInDetachedWindowEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetStartInDetachedWindowEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetLastModifiedDate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetLastModifierName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUptimeStartDate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUptime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingAutoMount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingAutoMount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingAutoMountCloudDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingAutoMountCloudDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingAutoMountNetworkDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingAutoMountNetworkDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingAutoMountRemovableDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingAutoMountRemovableDrives ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGuestSharingEnableSpotlight ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGuestSharingEnableSpotlight ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsHostSharingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetHostSharingEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShareAllHostDisks ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShareAllHostDisks ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShareUserHomeDir ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShareUserHomeDir ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsMapSharedFoldersOnLetters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetMapSharedFoldersOnLetters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShowTaskBar ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShowTaskBar ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsExcludeDock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExcludeDock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsMultiDisplay ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetMultiDisplay ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsScrResEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetScrResEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsDiskCacheWriteBack ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDiskCacheWriteBack ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsOsResInFullScrMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetOsResInFullScrMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsCloseAppOnShutdown ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetCloseAppOnShutdown ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSystemFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSystemFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsDisableAPIC ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDisableAPICSign ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUndoDisksMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUndoDisksMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAppInDockMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAppInDockMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetForegroundPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetForegroundPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetBackgroundPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetBackgroundPriority ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseDefaultAnswers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseDefaultAnswers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetDockIconType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetDockIconType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetConfirmationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetConfirmationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetPasswordProtectedOperationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetPasswordProtectedOperationsList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsAutoCompressEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoCompressEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetAutoCompressInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoCompressInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetFreeDiskSpaceRatio ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetFreeDiskSpaceRatio ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetVmInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetBiosType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetBiosType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsEfiSecureBootEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetEfiSecureBootEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExternalBootDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExternalBootDevice ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSmbiosBoardId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmbiosBoardId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSmbiosBuildVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmbiosBuildVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetSmbiosSystemSerialNumber ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSmbiosSystemSerialNumber ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsLockedSign ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CreateEvent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CreateUnattendedDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CreateUnattendedFloppy ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CreateUnattendedCd ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_InitiateDevStateNotifications ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ValidateConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UpdateSecurity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_InstallTools ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetToolsState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_InstallUtility ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsEncrypted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_Connect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_Disconnect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_CreateImage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_CopyImage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_ResizeImage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_Remove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_IsConnected ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetConnected ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_IsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_IsRemote ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetRemote ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetEmulatedType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetEmulatedType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetImagePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetImagePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetSysName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetSysName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetFriendlyName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetFriendlyName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetIfaceType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetIfaceType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetSubType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetSubType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetStackIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetStackIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetDefaultStackIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_GetOutputFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetOutputFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_IsPassthrough ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDev_SetPassthrough ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetDiskType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_SetDiskType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_IsSplitted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_SetSplitted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetDiskSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_SetDiskSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetSizeOnDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_SetPassword ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_IsEncrypted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_CheckPassword ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_AddPartition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetPartitionsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetPartition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHdPart_Remove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_GetOnlineCompactMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHd_SetOnlineCompactMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHdPart_GetSysName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevHdPart_SetSysName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetBoundAdapterIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetBoundAdapterIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetBoundAdapterName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetBoundAdapterName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetMacAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetMacAddressCanonical ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetMacAddress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GenerateMacAddr ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsAutoApply ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetAutoApply ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetNetAddresses ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetNetAddresses ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetDnsServers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetSearchDomains ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsConfigureWithDhcp ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetConfigureWithDhcp ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsConfigureWithDhcpIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetConfigureWithDhcpIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetDefaultGateway ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetDefaultGateway ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetDefaultGatewayIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetDefaultGatewayIPv6 ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetAdapterType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetAdapterType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsPktFilterPreventMacSpoof ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetPktFilterPreventMacSpoof) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsPktFilterPreventPromisc ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetPktFilterPreventPromisc ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_IsPktFilterPreventIpSpoof ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetPktFilterPreventIpSpoof ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_GetHostInterfaceName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevNet_SetHostInterfaceName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevUsb_GetAutoconnectOption ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevUsb_SetAutoconnectOption ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_GetAdvancedType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_SetAdvancedType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_GetOutputDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_SetOutputDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_GetMixerDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSound_SetMixerDev ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSerial_GetSocketMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmDevSerial_SetSocketMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_Remove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_SetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_GetPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_SetPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_GetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_SetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_IsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_SetEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_IsReadOnly ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlShare_SetReadOnly ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_Remove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_IsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_SetEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_GetWidth ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_SetWidth ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_GetHeight ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlScrRes_SetHeight ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_Remove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_SetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_GetIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_SetIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_GetSequenceIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_SetSequenceIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_IsInUse ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBootDev_SetInUse ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_Event ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_SetPos ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_Move ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_SetPosEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_MoveEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_AsyncSetPos ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevMouse_AsyncMove ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevKeyboard_SendKeyEvent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevKeyboard_SendKeyEventEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevKeyboard_SendKeyPressedAndReleased ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevKeyboard_SendOptimizationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_ConnectToVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_ConnectToVmEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_DisconnectFromVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_GetScreenBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_GetDisplayEncoding ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SetDisplayEncoding ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_GetScreenBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_GetScreenBufferEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_GetScreenBufferFormat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_LockForRead ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_Unlock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_IsSlidingMouseEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_GetScreenSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_GetScreenSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_GetDynResToolStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_NeedCursorData ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SendScreenSizeEvent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SetConfiguration ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_AsyncCaptureScreenRegionToFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_AsyncCaptureScaledScreenRegionToFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SyncCaptureScreenRegionToFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SyncCaptureScaledScreenRegionToFile ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_AsyncCaptureScaledScreenRegionToBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_AsyncCaptureScaledScreenRegionToBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SyncCaptureScaledScreenRegionToBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevSecondaryDisplay_SyncCaptureScaledScreenRegionToBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_GetAvailableDisplaysCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevDisplay_SetScreenSurface ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevAudio_StartStream ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDevAudio_StopStream ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ToolsSendShutdown ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ToolsGetShutdownCapabilities ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_GetAccessRights ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_IsInvalid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_IsVmWaitingForAnswer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_IsVncServerStarted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFoundVmInfo_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFoundVmInfo_IsOldConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFoundVmInfo_GetOSVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFoundVmInfo_GetConfigPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlFoundVmInfo_IsTemplate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAcl_IsAllowed ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAcl_GetAccessForOthers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAcl_SetAccessForOthers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAcl_GetOwnerName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAcl_IsCurrentSessionOwner ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmToolsInfo_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmToolsInfo_GetVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetTotalRamSize )	\
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetUsageRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetFreeRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetRealRamSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetTotalSwapSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetUsageSwapSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetFreeSwapSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetOsUptime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetDispUptime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetCpusStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetCpuStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetIfacesStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetIfaceStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetUsersStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetUserStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetDisksStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetDiskStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetProcsStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetProcStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStat_GetVmDataStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatCpu_GetCpuUsage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatCpu_GetTotalTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatCpu_GetUserTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatCpu_GetSystemTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatIface_GetSystemName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatIface_GetInDataSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatIface_GetOutDataSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatIface_GetInPkgsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatIface_GetOutPkgsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatUser_GetUserName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatUser_GetServiceName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatUser_GetHostName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatUser_GetSessionTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDisk_GetSystemName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDisk_GetUsageDiskSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDisk_GetFreeDiskSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDisk_GetPartsStatsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDisk_GetPartStat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDiskPart_GetSystemName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDiskPart_GetUsageDiskSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatDiskPart_GetFreeDiskSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetCommandName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetOwnerUserName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetTotalMemUsage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetRealMemUsage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetVirtMemUsage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetStartTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetTotalTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetUserTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetSystemTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatProc_GetCpuUsage ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlStatVmData_GetSegmentCapacity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLic_IsValid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLic_GetStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLic_GetLicenseKey ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetHostName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetProductVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetCmdPort ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetApplicationMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetServerUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetStartTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrvInfo_GetStartTimeMonotonic ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlNetSvc_GetStatus ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_FsGenerateEntryName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetSessionUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetRunningTaskCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetRunningTaskByIndex ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetServerUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetHostOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlLoginResponse_GetProductVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlRunningTask_GetTaskUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlRunningTask_GetTaskType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlRunningTask_GetTaskParametersAsString ) \
/*PrlDisk.h*/ \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CreateDiskEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ConfigurePhysical ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_OpenDiskEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CreateDisk_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_OpenDisk_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_IsBootable_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ConvertToCurrent_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SetSharedDirectory_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CreateDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_OpenDisk ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ConvertToCurrent ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SetSharedDirectory ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_WaitForCompletion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SetUserParameter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetUserParameter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CreateState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SwitchToState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_DeleteState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Write ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Free ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Read ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_FlushCache ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Compact ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CompactByBitmap ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_FixConsistency ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_IncreaseCapacity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_DecreaseCapacity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Coagulate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_IsCompactable ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetDiskInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetStatesTree ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStateParams_GetUid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStateParams_GetChildStateList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetSnapshotsTree ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetSnapshotsCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SetCachingPolicy ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_LinkedClone_Local ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_IsEncrypted ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_SetKey ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ChangeKeyEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_EncryptEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_Decrypt ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ConvertToCHS ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetDefaultLogicSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetDefaultPhysicalSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CalcDefaultBlockSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_CalcSplitPartSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetIdentify ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_ConvertToExtendFormat ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetTemporarySnapshotUID ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDisk_GetParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetUid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetUid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetLogicalSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetLogicalSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetPhysicalSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetPhysicalSectorSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetBlockSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetBlockSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetCHS ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetCHS ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetStorageList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_SetStorageList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskParams_GetSalt ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_GetImageType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_SetImageType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_GetImageName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_SetImageName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_GetStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_SetStart ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_SetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_GetReadOnly ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskStorageParams_SetReadOnly ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_GetDiskParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_SetDiskParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_GetDiskOpenFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_SetDiskOpenFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_GetDiskCallback ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDiskOpParams_SetDiskCallback ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_TisGetIdentifiers ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_TisGetRecord ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetUid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetText ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetData ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetTime ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlTisRecord_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUIEmuInput_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUIEmuInput_AddVKeys ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUIEmuInput_AddText ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UIEmuSendInput ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UIEmuSendText ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UIEmuSendScroll ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UIEmuQueryElementAtPos ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SubscribeToPerfStats )     \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_UnsubscribeFromPerfStats ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetPerfStats )             \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SubscribeToPerfStats )      \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_UnsubscribeFromPerfStats )  \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetPerfStats ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_AuthWithGuestSecurityDb ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmInfo_GetAdditionState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Compact ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CancelCompact ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ConvertDisks ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CancelConvertDisks ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOsesMatrix_GetSupportedOsesTypes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOsesMatrix_GetSupportedOsesVersions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlOsesMatrix_GetDefaultOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_HasRestriction ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetRestrictionInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlApi_CreatePackedProblemReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetUserName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetUserName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetUserEmail ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetUserEmail ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetClientVersion) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetClientVersion) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetDescription ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetReason ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetReason ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetScheme ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetArchiveFileName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetData ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetCombinedReportId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetCombinedReportId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_SetRating ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_GetRating ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_AsString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlReport_Assembly ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_InstallAppliance ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_CancelInstallAppliance ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_StopInstallAppliance ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlAppliance_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShowWindowsAppInDock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShowWindowsAppInDock ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedAppsGuestToHost ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedAppsGuestToHost ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedAppsHostToGuest ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedAppsHostToGuest ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShowGuestNotifications ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShowGuestNotifications ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsBounceDockIconWhenAppFlashes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetBounceDockIconWhenAppFlashes ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsPauseWhenIdle ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetPauseWhenIdle ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsWinSystrayInMacMenuEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetWinSystrayInMacMenuEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSwitchToFullscreenOnDemandEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSwitchToFullscreenOnDemandEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsVirtualLinksEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetVirtualLinksEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Authorise ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ChangePassword ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Encrypt ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Decrypt ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Archive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Unarchive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Pack ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Unpack ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SetProtection ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_RemoveProtection ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsProtected ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetTpmType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsArchived ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationDate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExpirationDate ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationDateEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsExpirationDateEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExpirationTimeCheckInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationTimeCheckInterval ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExpirationOfflineTimeToLive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationOfflineTimeToLive ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExpirationNote ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationNote ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetExpirationTrustedTimeServer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetExpirationTrustedTimeServer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetUsbIdentityCount ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetUsbIdentity ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsbIdent_GetSystemName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsbIdent_GetFriendlyName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsbIdent_GetVmUuidAssociation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlUsbIdent_GetAutoconnectAction ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetUsbIdentAssociation ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetUsbIdentAssociationWithAction ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_IsFeatureSupported ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsRamHotplugEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetRamHotplugEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LoginEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LoginWithParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ProxyLoginEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LoginLocalEx ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_LoginLocalWithParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_CreateCVSrc ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_RegEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_UnregEventHandler ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_SetLocalizedName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_Connect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_Disconnect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_Open ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_Close ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_LockBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_UnlockBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlCVSrc_GetBuffer ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetDiskFreeSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_RefreshServerInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsUseHostPrinters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUseHostPrinters ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSyncDefaultPrinter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSyncDefaultPrinter ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShowHostPrinterUI ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShowHostPrinterUI ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedCameraEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedCameraEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedBluetoothEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedBluetoothEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSharedSmartCardEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSharedSmartCardEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSupportUsb30Enabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSupportUsb30Enabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Move ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Connect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_Disconnect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_TerminalConnect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_TerminalDisconnect ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetVmConfig ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsAutoApplyIpOnly) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetAutoApplyIpOnly) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUnattendedInstallLocale ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUnattendedInstallLocale ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetUnattendedInstallEdition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetUnattendedInstallEdition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetMobileAdvancedAuthMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetMobileAdvancedAuthMode ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_GetPackageId ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SetVNCEncryption ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ToolsSetTaskBarVisibility ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_ToolsSetPowerSchemeSleepAbility ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_SendClipboardRequest ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_SendProblemReport ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_FromString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlHandle_ToString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlEvent_FromString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetBackupVmList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_GetBackupVmByPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_Begin ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_Commit ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_Rollback ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_GetSessionUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_GetInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupInfo_GetState ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupInfo_IsBootcamp ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupInfo_GetVmPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_GetParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_SetParams ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_SetLocationUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_GetLocationUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_SetLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_GetLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_SetChangeMonitoring ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_GetChangeMonitoring ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_SetLocationTimeout ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_GetLocationTimeout ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_SetOptions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupParam_GetOptions ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_GetFilesList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackup_SendProgress ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetDifferencesList ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetRestorePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetKind ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetType ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetLevel ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFile_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFileDiff_GetOffset ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlBackupFileDiff_GetSize ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSyncVmHostnameEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSyncVmHostnameEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsSyncSshIdsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetSyncSshIdsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetResourceQuota ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetResourceQuota ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetTravelModeEnterCondition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTravelModeEnterCondition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetTravelModeEnterThreshold ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTravelModeEnterThreshold ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_GetTravelModeQuitCondition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetTravelModeQuitCondition ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShowDevToolsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShowDevToolsEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_GetUsbAutoConnectOption ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlDispCfg_SetUsbAutoConnectOption ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsGestureSwipeFromEdgesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetGestureSwipeFromEdgesEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_IsShareHostLocationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmCfg_SetShareHostLocationEnabled ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_GetVmDirPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_SetVmDirPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_GetVmUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_SetVmUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_GetVmName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_SetVmName ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_GetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmRegisterParams_SetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetNetworkSettings ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetOsVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetArch ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetArch ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetMajorVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetMajorVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetMinorVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetMinorVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetPatchVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetPatchVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetBuildVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetBuildVersion ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_GetBuildAsString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVmGuestOsInfo_SetBuildAsString ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_EstimateConvertThirdPartyVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlSrv_ConvertThirdPartyVm ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_Create ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_GetSourcePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_SetSourcePath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_GetDestinationPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_SetDestinationPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_GetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertParams_SetFlags ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertResult_GetRequiredDiskSpace ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertResult_GetResultPath ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertResult_GetVmUuid ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlThirdPartyVmConvertResult_GetVmGuestOsInfo ) \
PRL_SDK_WRAP_FOR_EACH_ITERATOR( PrlVm_GetTotalSnapshotsSize ) \


#endif // PRL_SDK_WRAP_FOR_EACH
